# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lekko < Formula
  desc "A new way of working with dynamic configuration."
  homepage "https://lekko.com/"
  version "0.3.24"
  license "Apache-2.0"

  depends_on "buf"

  on_macos do
    if Hardware::CPU.arm?
      url "https://lekko-cli-releases.s3.amazonaws.com/v0.3.24/lekko_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c685bda0490718c3f1b562471b43bac2637815fae595e23896f2c3d565cff7cb"

      def install
        bin.install "lekko"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://lekko-cli-releases.s3.amazonaws.com/v0.3.24/lekko_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "4309371cf0627d9892c8bbfad7789024e88eb9fe1f04741dcde52a832366e87d"

      def install
        bin.install "lekko"
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://lekko-cli-releases.s3.amazonaws.com/v0.3.24/lekko_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ce125358d6e7d35b142df5f8ebf0993d648cc70254d879f38883f15f46f38045"

      def install
        bin.install "lekko"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://lekko-cli-releases.s3.amazonaws.com/v0.3.24/lekko_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "279ef2047744e7872383306a579a2d50d41d9f9cf743accdd081bd3de6142dfa"

      def install
        bin.install "lekko"
        # ...
      end
    end
  end

  test do
    system "#{bin}/lekko"
    # ...
  end
end
