# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../lib/custom_download_strategy"
class Lekko < Formula
  desc "A new way of working with dynamic configuration."
  homepage "https://lekko.com/"
  version "0.2.32"
  license "Apache-2.0"

  depends_on "buf"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lekkodev/cli/releases/download/v0.2.32/lekko_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "edf9ee74c21900f504bb6272c67b082bd98b919a3bfaa8df76d4eecbb85ca3ba"

      def install
        bin.install "lekko"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lekkodev/cli/releases/download/v0.2.32/lekko_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cd8fcca4cdebeeadba522526b238a7319387c1235571ab38db31a6f506f3d908"

      def install
        bin.install "lekko"
        # ...
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lekkodev/cli/releases/download/v0.2.32/lekko_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "96ae0ea4c8fe36dd479920b3565b081ed64b7b065554e8a4e2ac359873d6a904"

      def install
        bin.install "lekko"
        # ...
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lekkodev/cli/releases/download/v0.2.32/lekko_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2e860828ff7f7c35dcd8d767852cfda8e06fb37558d3b508d2040ad8235b0d7f"

      def install
        bin.install "lekko"
        # ...
      end
    end
  end

  test do
    system "#{bin}/lekko"
    # ...
  end
end
